name = "bjs-backend"
main = "src/main.ts"
compatibility_date = "2025-01-12"

compatibility_flags = [ "nodejs_compat_v2" ]

[triggers]
crons = ["0 8-21 * * *"] # trigger scheduled events every hour between 8am and 9pm

[[d1_databases]]
binding = "DB"
database_name = "bjs-db"
database_id = "e09c6185-8f37-4f94-8d58-911da022a725"

[observability]
enabled = true
head_sampling_rate = 1

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

